name: Deploy Backend to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Build the Spring Boot application
      - name: Build with Maven
        working-directory: server
        run: mvn clean package -DskipTests

      # Step 4: Securely copy the JAR file to the server
      - name: Copy JAR to DigitalOcean server
        uses: appleboy/scp-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: server/target/*.jar
          target: /root/app/

      # Step 5: Restart the application on the server
      - name: Restart Spring Boot application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar /root/app/*.jar > /root/app/log.txt 2>&1 &
